- name: Start container on webhook event
  hosts: localhost
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: launch playbook when start signal received 1
      condition: event.payload.title is search("visits-service") 
      throttle:
        group_by_attributes:
          - event.payload.service_title     # Corrected field name reference
        once_within: 10 minutes
      action:
        run_workflow_template:
          name: Correct_Application
          organization: Default
          post_events: true

    # - name: launch playbook when start signal received 1
    #   condition: event.payload.event_source is search("Mixed alert") 
    #   throttle:
    #     group_by_attributes:
    #       - event.payload.service_title     # Corrected field name reference
    #     once_within: 10 minutes
    #   action:
    #     run_job_template:
    #       name: StartContainer
    #       organization: Default
    #       post_events: true
