- name: Start container on webhook event
  hosts: localhost
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:

    - name: launch playbook when start signal received 1
      condition: event.payload.title == "KPI Alerts from Service: visits-service"
      throttle:
        group_by_attributes:
          - event.service_title      # "visits-service"
          - event.kpi_title          # "Visits Created"
          - event.itsiSeverity       # "critical"
        once_within: "10m"
      action:
        run_job_template:
          name: StartContainer
          organization: Default

    # - name: launch playbook when start signal received 2
    #   condition: event.payload.event_source == "Mixed alert"
    #   action:
    #     run_job_template:
    #       name: StartContainer
    #       organization: Default
