- name: Start container on webhook event
  hosts: localhost
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:

    - name: launch playbook when start signal received 1
      condition: event.payload._bkt == "itsi_grouped_alerts~0~0ED494E3-1C6A-44F1-B425-0F734103DFA0"
      action:
        run_job_template:
          name: StartContainer
          organization: Default

    - name: launch playbook when start signal received 2
      condition: event.payload.event_source == "Mixed alert"
      action:
        run_job_template:
          name: StartContainer
          organization: Default
