- name: Start container on webhook event
  hosts: localhost
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: launch playbook when start signal received
      condition: event.payload.search_name == "test"
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: Default
