---
- name: Check if api-gateway container is running
  hosts: all
  become: true
  tasks:

    - name: Alternative command-based check
      command: podman ps --filter name=api-gateway --format "{{.Names}}\t{{.Status}}"
      register: podman_check
