---
- name: Check if api-gateway container is running
  hosts: all
  become: true
  tasks:

    - name: command-based check
      command: podman ps -q --filter name=api-gateway
      register: podman_check

    - debug:
        msg: {{ podman_check }}
