- name: Create/Start the api-gateway container
  hosts: all
  gather_facts: false
  collections:
    - containers.podman
  tasks:

    - name: List running podman containers
      command: podman ps
      register: running_containers
      changed_when: false

    - name: Display running containers
      debug:
        msg: "{{ running_containers.stdout_lines }}"
        
    - name: List all podman containers (including stopped)
      command: podman ps -a
      register: all_containers
      changed_when: false
      
    - name: Display all containers
      debug:
        msg: "{{ all_containers.stdout_lines }}"
        
    - name: Get container details in JSON format
      command: podman ps --format json
      register: containers_json
      changed_when: false

  
    # - name: Start api-gateway container
    #   containers.podman.podman_container:
    #     name: api-gateway
    #     image: docker.io/springcommunity/spring-petclinic-api-gateway:latest
    #     state: stopped
    #     detach: true
    #     network:
    #       - petclinic-net
    #     publish:
    #       - "8180:8080"
    #       - "9016:9016"
    #     env:
    #       SPRING_PROFILES_ACTIVE: docker
    #       SPRING_JMX_ENABLED: "true"
    #       MANAGEMENT_METRICS_EXPORT_JMX_ENABLED: "true"
    #       MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
    #       JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=127.0.0.1"
