- name: Create/Start the api-gateway container
  hosts: all
  gather_facts: false
  collections:
    - containers.podman
  tasks:
    - name: List all running Podman containers
      community.general.podman_containers:
        state: list
      register: running_containers_output # Register the output to a variable

    - name: Display running containers
      debug:
        msg: "Currently running Podman containers: {{ running_containers_output.containers | default([]) | map(attribute='name') | list }}"
      # The 'containers' attribute holds details. We extract 'name' for display.
      # default([]) handles cases where 'containers' might be undefined or empty.

  
    # - name: Start api-gateway container
    #   containers.podman.podman_container:
    #     name: api-gateway
    #     image: docker.io/springcommunity/spring-petclinic-api-gateway:latest
    #     state: stopped
    #     detach: true
    #     network:
    #       - petclinic-net
    #     publish:
    #       - "8180:8080"
    #       - "9016:9016"
    #     env:
    #       SPRING_PROFILES_ACTIVE: docker
    #       SPRING_JMX_ENABLED: "true"
    #       MANAGEMENT_METRICS_EXPORT_JMX_ENABLED: "true"
    #       MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
    #       JAVA_TOOL_OPTIONS: "-Djava.rmi.server.hostname=127.0.0.1"
