- name: Create/Start the api-gateway container
  hosts: all
  gather_facts: false
  collections:
    - containers.podman
  tasks:

    - name: List running containers (basic format)
      command: podman ps
      register: podman_basic
      changed_when: false
